version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pethealth_db
    restart: always
    environment:
      POSTGRES_DB: pethealth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pethealth_data:/var/lib/postgresql/data

volumes:
  pethealth_data:
